name: Build keycloak-scim and release

on:
  push:
    branches:
      - "main"
      - "BR-485-keycloak-groups-filter"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.11
          cache-disabled: true

      - name: Get version
        run: echo "VERSION=$(./gradlew -q properties | grep '^version:' | cut -d' ' -f2)" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Create Release with jar file
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "keycloak-scim ${{ env.VERSION }} release"
          files: ./build/libs/*.jar
          generate_release_notes: true
